# Generated by Django 2.2.13 on 2020-07-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=15, verbose_name='New')),
                ('text', models.TextField(default='', max_length=3000, null=True, verbose_name='Detailed description')),
                ('created_at', models.DateField(default='', verbose_name='Created date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
