# Generated by Django 2.2.13 on 2020-07-30 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='QuickMemo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='QuickMemo',
            name='execution_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Execution date'),
        ),
    ]
